#debug: true

build:
  image: armdrone/drone-plugin-base
  commands:
    - apk update && apk add tar gzip curl
    - export VERSION=0.9.13
    - export URL=https://github.com/gogits/gogs/releases/download/v${VERSION}/linux_arm.zip
    - curl -L ${URL} > ./gogs.zip
    - unzip gogs.zip
    - ls -la . */

publish:
  docker:
#    environment:
#      - DOCKER_LAUNCH_DEBUG=true
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    file: Dockerfile.rpi
    repo: firecyberice/armhf-gogs
    tag:
      - latest
      - "0.9.13"
