#debug: true

publish:
  docker:
#    environment:
#      - DOCKER_LAUNCH_DEBUG=true
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    file: Dockerfile.rpi
    repo: firecyberice/armhf-gogs
    tag:
#      - latest
      - "0.9.13-rpi"
